package proyectomonedas;

import java.io.*;        //  Paquete de acceso a datos.
import java.awt.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.text.*;

public class Formulario1 extends javax.swing.JFrame {

    public Formulario1() {
        initComponents();
        ///////////////////
        Font f = new Font( "Consolas", Font.BOLD, 14 );
        list1.setFont(f);
        ///////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        list1 = new java.awt.List();
        jRadioCompra = new javax.swing.JRadioButton();
        jRadioVenta = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Casa de Cambio");

        jButton1.setText("Salida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setToolTipText("");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad:");

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar las cotizaciones");
        btnActualizar.setName(""); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        list1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        jRadioCompra.setText("Compra");
        jRadioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCompraActionPerformed(evt);
            }
        });

        jRadioVenta.setText("Venta");
        jRadioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLabel1)))
                        .addContainerGap(238, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioCompra)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioVenta)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel8)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioCompra)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioVenta)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)))
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
//        throws FileNotFoundException,
//            IOException {
        list1.clear();
        try {
            FileInputStream fis;   //  La clase "FileInputStream" sirve para
            //referir a archivos o conexiones (sockets)
            //de una PC.
            DataInputStream Datos; //  La clase "DataInputStream" sirve para
            //leer independientemente del hardware,
            //tipos de datos de una "corriente" o 
            //"stream" que en nuestro caso es un archivo.
            String renglon = null;

            //  Al instanciar o crear el objeto, ABRIMOS el archivo.
            fis = new FileInputStream("C:\\Temp\\Cotizaciones.txt");
            Datos = new DataInputStream(fis);

            //  USAMOS el archivo.
//            jList1 ListForm = new jList1(4,false);
//ArrayList<String> AL = new ArrayList<String>();
            renglon = Datos.readLine();  //  Leemos un registro.
            while (renglon != null) {  //  Es "null" si encuentra fin del archivo.
                System.out.println(renglon);
                list1.add(renglon);
//                AL.add(renglon);

                renglon = Datos.readLine();//  Leemos un registro.
            }
//jList1.setListData(AL.addAll()); .setListData(AL);
            //  CERRAMOS el archivo.
            fis.close();
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        //System.out.println(list1.getSelectedItem());
        if (jRadioVenta.isSelected()) {
            jLabel7.setText("");
            jLabel9.setText("");
            jLabel8.setText(list1.getSelectedItem().substring(0, 3));
            jLabel10.setText(list1.getSelectedItem().substring(10, 17));
        } else if (jRadioCompra.isSelected()) {
            jLabel8.setText("");
            jLabel10.setText("");
            jLabel7.setText(list1.getSelectedItem().substring(0, 3));
            jLabel9.setText(list1.getSelectedItem().substring(20));

        }
    }//GEN-LAST:event_list1ActionPerformed

    private void jRadioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCompraActionPerformed
        jRadioVenta.setSelected(false);
        jLabel7.setText(list1.getSelectedItem().substring(0, 3));
        jLabel9.setText(list1.getSelectedItem().substring(20));
        if (jRadioCompra.isSelected()) {
            jLabel3.setText("");
            jLabel8.setText("");
            jLabel10.setText("");
        }
    }//GEN-LAST:event_jRadioCompraActionPerformed

    private void jRadioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioVentaActionPerformed
        jRadioCompra.setSelected(false);
        jLabel8.setText(list1.getSelectedItem().substring(0, 3));
        jLabel10.setText(list1.getSelectedItem().substring(10, 17));
        if (jRadioVenta.isSelected()) {
            jLabel3.setText("");
            jLabel7.setText("");
            jLabel9.setText("");
        }
    }//GEN-LAST:event_jRadioVentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //  Evento que sucede al presionar el botón "Salida"
        dispose();         //  Libera recursos.
         System.exit(0);   //  Termina.
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //  Boton Aceptar.
        String x;
        double cantidad, precio, valorTotal;
        
        DecimalFormat df1 = new DecimalFormat( ",###.00" );

        cantidad = Double.parseDouble(jTextField1.getText());
        if( jLabel9.getText() != "" )
           precio = Double.parseDouble(jLabel9.getText());
        else
           precio = Double.parseDouble(jLabel10.getText());

        valorTotal= cantidad*precio;
        if( jRadioCompra.isSelected() )
           jLabel3.setText( "$ " + df1.format( valorTotal  ) );
        //   jLabel3.setText( "$ " + df1.format( String.valueOf( valorTotal ) ) );
        
        else
            if( jRadioVenta.isSelected() )
                   jLabel3.setText( jLabel8.getText() + " " +String.valueOf( valorTotal ) );
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       if(jTextField1.requestFocus(true) )
           jLabel3.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        //  Cuando enfocamos el jTextField1, limpiamos el jLabel3
        jLabel3.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioCompra;
    private javax.swing.JRadioButton jRadioVenta;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
